const VALID_WIDTHS = Object.freeze ([0, 1, 2, 4, 8]);

const DEFAULT_BALL_WIDTH  = 0;
const DEFAULT_BALL_HEIGHT = 0;
const DEFAULT_BALL_X      = 0;
const DEFAULT_BALL_Y      = 0;

const BALL_MUL_WIDTH  = 2;
const BALL_MUL_HEIGHT = 2;
const BALL_ADD_HEIGHT = 2;


export
{
	VALID_WIDTHS,

	DEFAULT_BALL_WIDTH,
	DEFAULT_BALL_HEIGHT,
	DEFAULT_BALL_X,
	DEFAULT_BALL_Y,

	BALL_MUL_WIDTH,
	BALL_MUL_HEIGHT,
	BALL_ADD_HEIGHT,
};
